- name: Installation docker
  block:
    - name: Uninstall all conflicting packages
      apt:
        name: "{{ item }}"
        state: absent
        purge: yes
      loop:
        - docker.io
        - docker-doc
        - docker-compose
        - docker-compose-v2
        - podman-docker
        - containerd
        - runc

    - name: Install required packages
      apt:
        name:
          - ca-certificates
          - curl
        state: present

    - name: Set up Docker's apt repository
      shell: |
        sudo install -m 0755 -d /etc/apt/keyrings
        sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
        sudo chmod a+r /etc/apt/keyrings/docker.asc
        echo \
          "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
          $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}") stable" | \
          sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
      register: setup_docker_repo
      changed_when: setup_docker_repo.rc == 0

    - name: Update apt package index
      apt:
        update_cache: yes
      when: setup_docker_repo.changed

    - name: Install the latest version of Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present