- name: Deploiement de k3s et helm
  hosts: all
  become: true
  vars:
    ansible_user: root
    ansible_password: bonjour
    ansible_become_user: root
    ansible_become_password: bonjour
    k3s_server_ip: "{{ hostvars['master'].ansible_host }}"
    ansible_connection: ssh
  roles:
    - installation_helm_k3s