- name: Deploiement de k3s et helm
  hosts: all
  become: true
  vars:    
    ansible_become_user: root
    ansible_become_password: bonjour
    k3s_server_ip: 172.18.50.111
    ansible_connection: ssh
  roles:
    - installation_helm_k3s