- name: Deploiement de k3s et helm
  hosts: 127.0.0.1
  become: true
  vars:
    ansible_user: root
    ansible_password: bonjour
    ansible_become_user: root
    ansible_become_password: bonjour
  roles:
    - installation_helm_k3s